config/routes.rb
Rails.application.routes.draw do
  root 'events#index'
  devise_for :users
  resources :events
  resources :invitations
  put '/event/:id/attend', to: 'events#attend', as: 'attend'
  get '/user/:id', to: 'users#show', as: 'upcoming_events'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :invitations, dependent: :destroy
  has_many :attendees, through: :invitations
  
  validates :title, length: { in: 3..50 }, presence: true
  validates :location, length: { in: 3..90 }, presence: true
  validates :date, presence: true
  validates :creator_id, presence:true

    
  def past
    self.date < Date.today
  end

  def future
    self.date >= Date.today
  end

end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: "User"
  belongs_to :event

  validates :attendee_id, presence: true, uniqueness: {scope: :event_id}
  validates :event, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :password, length: { in: 6..16 }, presence: true
  validates :username, length: { in: 4..12 }, presence: true, uniqueness: { case_sensitive: false }
  # only allow letter, number, underscore and punctuation.
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validates :email, presence: true, uniqueness: true

  has_many :posts, dependent: :destroy

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end

  
  has_many :created_events, foreign_key: :creator_id, class_name: "Event", dependent: :destroy
  has_many :invitations, foreign_key: :attendee_id
  has_many :attending_events, through: :invitations, source: :event
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: [:login, :password]
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event, only: %i[ show edit update destroy ]
  
  # GET /events 
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
    @event = Event.find(params[:id])
    session[:current_event_id] = @event.id
  end 

  # GET /events/new
  def new
   @event = current_user.created_events.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # ATTEND - Custom method for attending events
  def attend
    Invitation.create(attendee: current_user, event_id: session[:current_event_id])
    redirect_to event_path(session[:current_event_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:title, :location, :date, :creator_id)
    end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  
  def index
    @appointments = Appointment.all
  end
  
  # GET /invitations/new
  def new
  end
 
   # GET /invitations/1/edit
  def edit
  end
 
  # POST /invitations or /invitations.json
  def create
    @invitation = Invitation.create(attendee: current_user, event_id: session[:current_event_id])
  end

  private
  # Use callbacks to share common setup or constraints between actions.

  # Only allow a list of trusted parameters through.
  def invitation_params
    params.require(:invitation).permit(:attendee_id, :event_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_with model: @event do |form| %>
    <%= form.label :title, "Title:" %>
    <%= form.text_field :title, placeholder: "Event Title" %>
    <br><br>
    <%= form.label :location, "Location:"%>
    <%= form.text_area :location, placeholder: "Event Location"  %>
    <br><br>
    <%= form.label :date, "Date:"%>
    <%= form.date_field :date  %>
    <br><br>
    <%= form.submit "Create" %>
  <% end %>

<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form', event: @event %>

<button class="nav-button">
  <%= link_to 'Show', @event %>
</button>

<button class="nav-button">
  <%= link_to 'Back', events_path %>
</button>

app/views/events/index.html.erb
<div class="events-section">
  <h2 class="events-section-title">Upcoming Events</h2>
  <div class="events-wrapper">
    <% @events.all.each do |event| %>
      <% if event.future%>
        <div class="event-container">
          <%= link_to event.title, event_path(event), class:"event-title" %>
          <p class="event-location">
            <span class="attribute-descriptor">Location: </span>
            <%= event.location %>
          </p>
          <p class="event-date">
            <span class="attribute-descriptor">Date: </span>
            <%= event.date.to_formatted_s(:rfc822) %>
          </p>
          <p class="event-creator">
            <span class="attribute-descriptor">Host: </span>
            <%= event.creator[:username] %>
          </p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>


<div class="events-section">
  <h2 class="events-section-title">Past Events</h2>
  <div class="events-wrapper">
    <% @events.order(:date).all.each do |event| %>
      <% if event.past %>
        <div class="event-container">
          <%= link_to event.title, event_path(event), class:"event-title" %>
          <p class="event-location">
            <span class="attribute-descriptor">Location: </span>
            <%= event.location %>
          </p>
          <p class="event-date">
            <span class="attribute-descriptor">Date: </span>
            <%= event.date.to_formatted_s(:rfc822) %>
          </p>
          <p class="event-creator">
            <span class="attribute-descriptor">Host: </span>
            <%= event.creator[:username] %>
          </p>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<h1> <%= @event.title %> </h1>
<h3>Event details </h3>
<p class="event-location">
  <span class="attribute-descriptor">Location: </span>
  <%= @event.location %>
</p>
<p class="event-date">
  <span class="attribute-descriptor">Date: </span>
  <%= @event.date.to_formatted_s(:long_ordinal) %>
</p>
<p class="event-creator">
  <span class="attribute-descriptor">Host: </span>
  <%= @event.creator[:username] %>
</p>

<% if user_signed_in? %>
  <p class="event-attendees">
    <span class="attribute-descriptor">Attendees: </span>
    <% @event.attendees.all.each do |attendee| %>
      <p> <%= attendee.username %> </p>
    <% end %>
  </p>

  <button class="nav-button">
    <%= link_to 'Attend Event', attend_path(session[:current_event_id]), {:method => :put} %>
  </button>

<% end%>


<button class="nav-button">
  <%= link_to 'Back', events_url %>
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="main-wrapper">

      <header class="page-header">
        <%= link_to "Private Events", root_path, class: "logo" %>
        <nav class="page-navbar">
          <% if user_signed_in? %>
              <%= link_to 'Create Event', new_event_path, class: "nav-link create-event"  %>
              <%= link_to "Your Events", upcoming_events_path(current_user[:id]), class: "nav-link"  %>
              <%= link_to current_user.username, edit_user_registration_path, class: "nav-link"  %>
              <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path, class: "nav-link"  %>
            <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link"  %>
          <% end %>
        </nav>
      </header>
      <div class="body-wrapper">
        <% unless notice.nil? %>
          <p id="notice"><%= notice %></p>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <p class="username"><%= user.username %></p>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
  <div class="events-section">
    <h2 class="events-section-title">Events You've Created</h2>
    <div class="events-wrapper">
      <% @user.created_events.order(:date).all.each do |event| %>
        <div class="event-container">
          <%= link_to event.title, event_path(event), class:"event-title" %>
          <p class="event-location">
            <span class="attribute-descriptor">Location: </span>
            <%= event.location %>
          </p>
          <p class="event-date">
            <span class="attribute-descriptor">Date: </span>
            <%= event.date.to_formatted_s(:rfc822) %>
          </p>
        </div>
      <% end %>
    </div>
  </div>

    <div class="events-section">
    <h2 class="events-section-title">Upcoming Events You're Attending</h2>
    <div class="events-wrapper">
      <% @user.attending_events.order(:date).all.each do |event| %>
        <% if event.future %>
          <div class="event-container">
            <%= link_to event.title, event_path(event), class:"event-title" %>
            <p class="event-location">
              <span class="attribute-descriptor">Location: </span>
              <%= event.location %>
            </p>
            <p class="event-date">
              <span class="attribute-descriptor">Date: </span>
              <%= event.date.to_formatted_s(:rfc822)  %>
            </p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>

      <div class="events-section">
    <h2 class="events-section-title">Events You've Attended</h2>
    <div class="events-wrapper">
      <% @user.attending_events.order(:date).all.each do |event| %>
        <% if event.past %>
          <div class="event-container">
            <%= link_to event.title, event_path(event), class:"event-title" %>
            <p class="event-location">
              <span class="attribute-descriptor">Location: </span>
              <%= event.location %>
            </p>
            <p class="event-date">
              <span class="attribute-descriptor">Date: </span>
              <%= event.date.to_formatted_s(:rfc822) %>
            </p>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>